# Generated by Django 3.0.5 on 2025-07-05 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_auto_20210213_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='age',
            field=models.PositiveIntegerField(default=25, help_text='Age must be between 18 and 65 years', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)]),
            preserve_default=False,
        ),
    ]
