# Generated by Django 3.0.5 on 2025-07-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time profile was updated'),
        ),
    ]
