# Generated by Django 3.0.5 on 2025-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_auto_20250705_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='fulfilled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorrequest',
            name='donation_confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorrequest',
            name='donation_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorrequest',
            name='donation_verification_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded to Donors'), ('Accepted', 'Accepted by Donor'), ('Approved', 'Approved by Admin'), ('Fulfilled', 'Fulfilled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
