# Generated by Django 3.0.5 on 2025-07-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0006_auto_20250705_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='fulfilled_date',
        ),
        migrations.RemoveField(
            model_name='donorrequest',
            name='donation_confirmation_date',
        ),
        migrations.RemoveField(
            model_name='donorrequest',
            name='donation_verification_code',
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded to Donors'), ('Accepted', 'Accepted by Donor'), ('Donation_Pending', 'Donation Pending'), ('Donation_Confirmed', 'Donation Confirmed'), ('Approved', 'Approved by Admin'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='donorrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Donation_Pending', 'Donation Pending'), ('Donation_Confirmed', 'Donation Confirmed'), ('Rejected', 'Rejected'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
